export declare const THUMBNAIL = "thumbnail.thumbnails";
export declare const THUMBNAILS = "thumbnail.musicThumbnailRenderer.thumbnail.thumbnails";
export declare const CONTENT = "contents[0]";
export declare const RUN_TEXT = "runs[0].text";
export declare const TAB_CONTENT = "tabs[0].tabRenderer.content";
export declare const TAB_1_CONTENT = "tabs[1].tabRenderer.content";
export declare const SINGLE_COLUMN = "contents.singleColumnBrowseResultsRenderer";
export declare const SINGLE_COLUMN_TAB = "contents.singleColumnBrowseResultsRenderer.tabs[0].tabRenderer.content";
export declare const SECTION_LIST = "sectionListRenderer.contents";
export declare const SECTION_LIST_ITEM = "sectionListRenderer.contents[0]";
export declare const ITEM_SECTION = "itemSectionRenderer.contents[0]";
export declare const MUSIC_SHELF = "musicShelfRenderer";
export declare const GRID = "gridRenderer";
export declare const GRID_ITEMS = "gridRenderer.items";
export declare const MENU = "menu.menuRenderer";
export declare const MENU_ITEMS = "menu.menuRenderer.items";
export declare const MENU_LIKE_STATUS = "menu.menuRenderer.topLevelButtons[0].likeButtonRenderer.likeStatus";
export declare const MENU_SERVICE = "menuServiceItemRenderer.serviceEndpoint";
export declare const TOGGLE_MENU = "toggleMenuServiceItemRenderer";
export declare const MORE_BUTTON = "moreContentButton.buttonRenderer";
export declare const PLAY_BUTTON = "overlay.musicItemThumbnailOverlayRenderer.content.musicPlayButtonRenderer";
export declare const NAVIGATION_BROWSE = "navigationEndpoint.browseEndpoint";
export declare const NAVIGATION_BROWSE_ID = "navigationEndpoint.browseEndpoint.browseId";
export declare const NAVIGATION_PARAMS = "navigationEndpoint.browseEndpoint.params";
export declare const PAGE_TYPE = "browseEndpointContextSupportedConfigs.browseEndpointContextMusicConfig.pageType";
export declare const NAVIGATION_PAGE_TYPE = "navigationEndpoint.browseEndpoint.browseEndpointContextSupportedConfigs.browseEndpointContextMusicConfig.pageType";
export declare const NAVIGATION_VIDEO_ID = "navigationEndpoint.watchEndpoint.videoId";
export declare const NAVIGATION_PLAYLIST_ID = "navigationEndpoint.watchEndpoint.playlistId";
export declare const NAVIGATION_WATCH_PLAYLIST_ID = "navigationEndpoint.watchPlaylistEndpoint.playlistId";
export declare const NAVIGATION_VIDEO_TYPE = "watchEndpoint.watchEndpointMusicSupportedConfigs.watchEndpointMusicConfig.musicVideoType";
export declare const PLAY_WATCH = "playNavigationEndpoint.watchEndpoint";
export declare const PLAY_VIDEO_ID = "playNavigationEndpoint.watchEndpoint.videoId";
export declare const PLAY_PLAYLIST_ID = "playNavigationEndpoint.watchEndpoint.playlistId";
export declare const HEADER_DETAIL = "header.musicDetailHeaderRenderer";
export declare const DESCRIPTION_SHELF = "musicDescriptionShelfRenderer";
export declare const DESCRIPTION = "description.runs[0].text";
export declare const CAROUSEL = "musicCarouselShelfRenderer";
export declare const IMMERSIVE_CAROUSEL = "musicImmersiveCarouselShelfRenderer";
export declare const CAROUSEL_CONTENTS = "musicCarouselShelfRenderer.contents";
export declare const CAROUSEL_CONTAINER = "header.musicCarouselShelfBasicHeaderRenderer";
export declare const CAROUSEL_TITLE = "header.musicCarouselShelfBasicHeaderRenderer.title.runs[0]";
export declare const CAROUSEL_SUBTITLE = "header.musicCarouselShelfBasicHeaderRenderer.strapline.runs[0]";
export declare const CAROUSEL_THUMBNAILS = "header.musicCarouselShelfBasicHeaderRenderer.thumbnail.musicThumbnailRenderer.thumbnail.thumbnails";
export declare const FRAMEWORK_MUTATIONS = "frameworkUpdates.entityBatchUpdate.mutations";
export declare const TITLE = "title.runs[0]";
export declare const TITLE_TEXT = "title.runs[0].text";
export declare const TEXT_RUNS = "text.runs";
export declare const TEXT_RUN = "text.runs[0]";
export declare const TEXT_RUN_TEXT = "text.runs[0].text";
export declare const SUBTITLE = "subtitle.runs[0].text";
export declare const SUBTITLE2 = "subtitle.runs[2].text";
export declare const SUBTITLE3 = "subtitle.runs[4].text";
export declare const THUMBNAIL_RENDERER = "thumbnailRenderer.musicThumbnailRenderer.thumbnail.thumbnails";
export declare const THUMBNAIL_CROPPED = "thumbnail.croppedSquareThumbnailRenderer.thumbnail.thumbnails";
export declare const FEEDBACK_TOKEN = "feedbackEndpoint.feedbackToken";
export declare const SINGLE_BADGE_PATH = "musicInlineBadgeRenderer.accessibilityData.accessibilityData.label";
export declare const BADGE_PATH = "0.musicInlineBadgeRenderer.accessibilityData.accessibilityData.label";
export declare const BADGE_LABEL = "badges.0.musicInlineBadgeRenderer.accessibilityData.accessibilityData.label";
export declare const SUBTITLE_BADGE_LABEL = "subtitleBadges.0.musicInlineBadgeRenderer.accessibilityData.accessibilityData.label";
export declare const SINGLE_BADGE_LABEL = "subtitleBadge.0.musicInlineBadgeRenderer.accessibilityData.accessibilityData.label";
export declare const CATEGORY_TITLE = "musicNavigationButtonRenderer.buttonText.runs";
export declare const CATEGORY_PARAMS = "musicNavigationButtonRenderer.clickCommand.browseEndpoint.params";
export declare const CATEGORY_COLOR = "musicNavigationButtonRenderer.solid.leftStripeColor";
export declare const MRLIR = "musicResponsiveListItemRenderer";
export declare const MTRIR = "musicTwoRowItemRenderer";
export declare const MTCIR = "musicTwoColumnItemRenderer";
export declare const TASTE_PROFILE_ITEMS = "contents.tastebuilderRenderer.contents";
export declare const TASTE_PROFILE_ARTIST = "title.runs";
export declare const SECTION_LIST_CONTINUATION = "continuationContents.sectionListContinuation";
export declare const MENU_PLAYLIST_ID = "menu.menuRenderer.items.0.menuNavigationItemRenderer.navigationEndpoint.watchPlaylistEndpoint.playlistId";
export declare const MRLITFC = "musicResponsiveListItemFlexColumnRenderer.text";
export declare const TWO_COLUMN_RESULTS = "twoColumnBrowseResultsRenderer";
export declare const RESPONSIVE_HEADER = "musicResponsiveHeaderRenderer";
interface ObjectWithNested {
    [key: string]: any;
    [key: number]: any;
}
type ObjectList = Array<{
    [key: string]: any;
} | ObjectWithNested>;
export declare function find_object_by_key(objectList: ObjectList, key: string, nested?: string, isKey?: boolean): {
    [key: string]: any;
} | null;
export declare function find_objects_by_key(object_list: any, key: string, nested?: string): any[];
export declare function find_object_by_icon_name(objectList: ObjectList, key: string, icons: string | string[]): ObjectWithNested | null | undefined;
export {};
//# sourceMappingURL=nav.d.ts.map