on:
  push:
    branches:
      - 'APM'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG_VERSION::${GITHUB_REF/refs\/tags\//}

      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"

      - name: npm build
        run: deno run -A ./scripts/npm.ts ${{steps.get_tag_version.outputs.TAG_VERSION}}

      - name: Push Build to Github
        run: |
          cd npm
          git init
          git branch -m apm-release
          git remote add origin https://${{ secrets.TOKEN }}@github.com/lovegaoshi/muse.git
          git add .
          git config --global user.email "love@gaoshi.com"
          git config --global user.name "gaoshi"
          git commit -m 'release'
          git push --set-upstream origin apm-release --force

